version: '3.8'

services:
  process-exporter:
    image: ncabatoff/process-exporter
    container_name: process-exporter
    privileged: true
    ports:
      - "9256:9256"
    volumes:
      - /proc:/host/proc
      - process-exporter-config:/process-exporter.yml
    configs:
      - source: "process-exporter-config"
        target: "/process-exporter.yml"
    command:
      - --procfs
      - /host/proc
      - -config.path
      - /process-exporter.yml
    restart: unless-stopped
