version: '3.9'

services:
  process-exporter:
    image: ncabatoff/process-exporter
    container_name: process-exporter
    privileged: true
    ports:
      - "9256:9256"
    volumes:
      - /proc:/host/proc
      - ./process-exporter.yml:/process-exporter-config
    command:
      - --procfs
      - /host/proc
      - -config.path
      - /process-exporter.yml
    restart: unless-stopped

configs:
  process-exporter-config:
    file: ./process-exporter.yml
